### ISSUE TITLE
Refresh don't update "latest template" in ComboBox

### ISSUE THREAD

**Issue by kruppe** [nkristek/Stein#11]
Stein is open and for product last temp ist selected, ie. XYZ (tmp 014).
Meantime new setup ist copied, ie. XYZ (tmp 015).
Refresh command is executed.
new setup is in the list, but as "preselected" still XYZ (tmp 014).

**Comment by nkristek** [comment]
This was on the bug list, that after an install/uninstall it would execute a refresh and select the newest installer bundle. I will change this back to the old behaviour.
