### ISSUE TITLE
Rename folder during installation leads to strange notification behavior

### ISSUE THREAD

**Issue by kruppe** [nkristek/Stein#16]
During installation folder was renamed.
For not processed setups message box with information that setup file could not be found was shown.
Then message box was shown one more time (don't remember what message was shown).
In the end following message box was shown:

![image](https://user-images.githubusercontent.com/2216841/35908540-4d7f4dae-0bf1-11e8-911c-53323a45e0a7.png)

Checked logs folder. It contains error log with exactly the same message.
Additionally logged error message does not contain exception stack trace.

**Comment by nkristek** [comment]
This should have got fixed by commit e754a5b4 which added a File.Exists check before starting an install process. To track the error in the future, a stacktrace will now be added to the error message when an error is logged.

**Comment by nkristek** [comment]
I will close this issue since it didn't happen again. Feel free to reopen it again when the issue occurs again.
