### ISSUE TITLE
Stein failes to start

### ISSUE THREAD

**Issue by benruehl** [nkristek/Stein#25]
I have logged in to a system with a different domain account than usual. Stein is already installed (probably installed for every user) but fails to start. Starting the .exe brings up Windows' request for admin privileges which I confirm. Afterwards, simply nothing happens. There is no window opening, no flickering or similar.
When I delete the config file in %appdata%, Stein opens its window again but continues to show me a `NullReferenceException` in a MessageBox every time I perform any action. Unfortunately, I cannot log in 
to the system using the old domain account in order to test whether it works on that side.
I took the config file to a different machine where Stein was already installed as well. On that system everything works fine. Stein starts normally and processes the config file without errors. I cannot tell what might be the difference between those systems that causes this exception.

System: Windows 7
Version: 1.0.3 and 1.2.3

[Log and Config.zip](https://github.com/nkristek/Stein/files/2869451/Log.and.Config.zip)

**Comment by nkristek** [comment]
I did a major refactoring in 8ba210f which is still work in progress but it should hopefully address these issues.

**Comment by nkristek** [comment]
Most of the improvements are done. Please test it again with the just released v2.0-beta1 release.
For now, I will close this issue, feel free to reopen it if the issue still persists.
