### ISSUE TITLE
Show welcome view at first application start

### ISSUE THREAD

**Issue by nkristek** [nkristek/Stein#27]
Show a view explaining the features etc. when the application is first launched.

**Comment by hotz07** [comment]
Just add the Loaded Event.
       private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("Welcom");
        }

**Comment by nkristek** [comment]
Thank you for your comment. 
As a welcome dialog I thought more of a dialog explaining what you can do with Stein, maybe add the first installer source (normally done by the + button), etc. 
I really tried to get away from showing small dialogs via `MessageBox.Show` simply because it doesn't support any theming and generally looks a bit off. Also they only support showing text with an optional icon (info, error, alert, etc.) and you can't select text in those dialogs.
An example, on how I would like the welcome dialog to be implemented, would be the dialog for showing exceptions. 
I made a custom dialog which allows for the text to be selected, has a copy button which automatically copies the contents in the clipboard, supports theming and allows changes to the layout if needed.

Relevant files/lines of the `ExceptionDialog` are:
- [ExceptionDialog.xaml](https://github.com/nkristek/Stein/blob/master/src/Stein.Views/ExceptionDialog.xaml)
- [ExceptionView.xaml.cs](https://github.com/nkristek/Stein/blob/master/src/Stein.Views/ExceptionView.xaml.cs)
- [ExceptionView.xaml](https://github.com/nkristek/Stein/blob/master/src/Stein.Views/ExceptionView.xaml)
- [ExceptionView.xaml.cs](https://github.com/nkristek/Stein/blob/master/src/Stein.Views/ExceptionView.xaml.cs)
- [Views.xaml](https://github.com/nkristek/Stein/blob/master/src/Stein.Views/Views.xaml) (adding entries for ExceptionDialog and ExceptionView)
- [ExceptionDialogModel.cs](https://github.com/nkristek/Stein/blob/master/src/Stein.ViewModels/ExceptionDialogModel.cs)
- [ExceptionViewModel.cs](https://github.com/nkristek/Stein/blob/master/src/Stein.ViewModels/ExceptionViewModel.cs)
- [CopyExceptionDetailsToClipboardCommand.cs](https://github.com/nkristek/Stein/blob/master/src/Stein.ViewModels/Commands/ExceptionViewModelCommands/CopyExceptionDetailsToClipboardCommand.cs)
- [ViewModelService.cs](https://github.com/nkristek/Stein/blob/50c075a502a5afba6ae62b7552e1386774a1911c/src/Stein.ViewModels/Services/ViewModelService.cs#L139-L188) (adding case for ExceptionDialogModel)

Now you can show an exception like this.
```cs
var exceptionDialogModel = viewModelService.CreateViewModel<ExceptionDialogModel>(null, exception);
var dialogResult = dialogService.ShowDialog(exceptionDialogModel);
```

This would imply creating/modifying:
- create WelcomeDialog.xaml + WelcomeDialog.xaml.cs
- modify Views.xaml: add entry for WelcomeDialog
- create WelcomeDialogModel.cs
- modify ViewModelService.cs: add case for WelcomeDialogModel in [CreateViewModel](https://github.com/nkristek/Stein/blob/50c075a502a5afba6ae62b7552e1386774a1911c/src/Stein.ViewModels/Services/ViewModelService.cs#L64-L92)
- optionally create Commands for extra functionality
- modify App.xaml.cs: show dialog, when the configuration fails to load ([here](https://github.com/nkristek/Stein/blob/50c075a502a5afba6ae62b7552e1386774a1911c/src/Stein/App.xaml.cs#L57))

I just thought this would be a great issue for anybody which wants to contribute, since it doesn't involve the installer file handling, which is a bit difficult.
