### ISSUE TITLE
Usage of folder icon not clear

### ISSUE THREAD

**Issue by kruppe** [nkristek/Stein#35]
what is the meaning of folder icon?
have clicked it - was thinking, that can change folder - but can only browse folders, but selection does not work...

![stein - folder icon](https://user-images.githubusercontent.com/2216841/72875670-0ebad200-3cf5-11ea-903f-271f4febee43.png)

**Comment by nkristek** [comment]
This is only meant as a link to the selected folder (like a shortcut). It is only possible to change the folder from the Edit dialog. When clicking the GitHub icon for a repository based entry, it opens the web browser instead.

**Comment by kruppe** [comment]
then, for not github would be better with explorer...

**Comment by nkristek** [comment]
Could you please elaborate on what you mean exactly?

**Comment by kruppe** [comment]
ok... now I got the idea (and forget my "explorer" comment)... should I just close as not relevant?
