### ISSUE TITLE
Settings are not persisted

### ISSUE THREAD

**Issue by kruppe** [nkristek/Stein#37]
With clean installation of Stein settings are not persisted.

1. Delete "c:\Users\user_name\AppData\AppData\Roaming\Stein" if exists
2. Install Stein
3. Configure directory of product to install
4. Exit Stein
5. Start Stein -> no configuration

In "...\Roaming\Stein" exists only only config.v2.xml.
Before deleting of Stein directory I archived its content with all files.
As soon as I copied config.xml to newly created Stein dir, configuration was shown.
I think that without config.xml loading of settings for products is not working at all.

It can be reproduced at least from version 2.0

**Comment by nkristek** [comment]
Thanks for reporting, can you please check if there are any errors in the logs?

**Comment by kruppe** [comment]
Have made it almost clear - deleted logs dir & config.xml. only config.v2.xml in Stein dir.
One more time reproduced behavior.
Logs were not generated.
